#ifndef ROOTOS_KEYCODES_H
#define ROOTOS_KEYCODES_H


typedef enum
{
    ROOT_KEY_UNKNOWN = 0,

    ROOT_KEY_ESCAPE,

    ROOT_KEY_F1,
    ROOT_KEY_F2,
    ROOT_KEY_F3,
    ROOT_KEY_F4,
    ROOT_KEY_F5,
    ROOT_KEY_F6,
    ROOT_KEY_F7,
    ROOT_KEY_F8,
    ROOT_KEY_F9,
    ROOT_KEY_F10,
    ROOT_KEY_F11,
    ROOT_KEY_F12,

    ROOT_KEY_GRAVE,

    ROOT_KEY_1,
    ROOT_KEY_2,
    ROOT_KEY_3,
    ROOT_KEY_4,
    ROOT_KEY_5,
    ROOT_KEY_6,
    ROOT_KEY_7,
    ROOT_KEY_8,
    ROOT_KEY_9,
    ROOT_KEY_0,

    ROOT_KEY_MINUS,
    ROOT_KEY_EQUAL,

    ROOT_KEY_BACKSPACE,
    ROOT_KEY_TAB,

    ROOT_KEY_Q,
    ROOT_KEY_W,
    ROOT_KEY_E,
    ROOT_KEY_R,
    ROOT_KEY_T,
    ROOT_KEY_Y,
    ROOT_KEY_U,
    ROOT_KEY_I,
    ROOT_KEY_O,
    ROOT_KEY_P,

    ROOT_KEY_LEFT_BRACKET,
    ROOT_KEY_RIGHT_BRACKET,

    ROOT_KEY_ENTER,

    ROOT_KEY_LEFT_CTRL,

    ROOT_KEY_A,
    ROOT_KEY_S,
    ROOT_KEY_D,
    ROOT_KEY_F,
    ROOT_KEY_G,
    ROOT_KEY_H,
    ROOT_KEY_J,
    ROOT_KEY_K,
    ROOT_KEY_L,

    ROOT_KEY_SEMICOLON,
    ROOT_KEY_APOSTROPHE,
    ROOT_KEY_BACKSLASH,

    ROOT_KEY_LEFT_SHIFT,

    ROOT_KEY_Z,
    ROOT_KEY_X,
    ROOT_KEY_C,
    ROOT_KEY_V,
    ROOT_KEY_B,
    ROOT_KEY_N,
    ROOT_KEY_M,

    ROOT_KEY_COMMA,
    ROOT_KEY_DOT,
    ROOT_KEY_SLASH,

    ROOT_KEY_RIGHT_SHIFT,

    ROOT_KEY_ISO_LTGT,

    ROOT_KEY_LEFT_ALT,
    ROOT_KEY_SPACE,

    ROOT_KEY_CAPS_LOCK,
    ROOT_KEY_NUM_LOCK,
    ROOT_KEY_SCROLL_LOCK,

    ROOT_KEY_KP_0,
    ROOT_KEY_KP_1,
    ROOT_KEY_KP_2,
    ROOT_KEY_KP_3,
    ROOT_KEY_KP_4,
    ROOT_KEY_KP_5,
    ROOT_KEY_KP_6,
    ROOT_KEY_KP_7,
    ROOT_KEY_KP_8,
    ROOT_KEY_KP_9,

    ROOT_KEY_KP_DOT,
    ROOT_KEY_KP_PLUS,
    ROOT_KEY_KP_MINUS,
    ROOT_KEY_KP_MULTIPLY,
    ROOT_KEY_KP_DIVIDE,
    ROOT_KEY_KP_ENTER,

    ROOT_KEY_RIGHT_CTRL,
    ROOT_KEY_RIGHT_ALT,

    ROOT_KEY_INSERT,
    ROOT_KEY_DELETE,

    ROOT_KEY_HOME,
    ROOT_KEY_END,

    ROOT_KEY_PAGE_UP,
    ROOT_KEY_PAGE_DOWN,

    ROOT_KEY_LEFT,
    ROOT_KEY_RIGHT,
    ROOT_KEY_UP,
    ROOT_KEY_DOWN,

    ROOT_KEY_COUNT

} RootKey;


#endif